name: 更新 Clash/adobe.list

on:
  # 每 3 天运行一次
  schedule:
    - cron: '0 0 */3 * *'
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 下载 Adobe 规则
        run: |
          #curl -L https://raw.githubusercontent.com/ignaciocastro/adobe-is-dumb/main/list.txt -o adobe.list
          curl -L https://a.dove.isdumb.one/list.txt -o adobe.list
          sed -i 's/0\.0\.0\.0 /DOMAIN,/g' adobe.list
          # 检查Clash文件夹是否存在，如果不存在则创建
          if [ ! -d "Clash" ]; then
            mkdir Clash
          fi
          mv adobe.list Clash/

      - name: 更新adobe.list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Clash/adobe.list
          git commit -m "Downloaded file on $(date "+%Y/%m/%d %H:%M:%S")"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          git push
